# Generated by Django 3.0.2 on 2020-01-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200120_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='short_name',
            field=models.CharField(default='no_project_name', max_length=50),
        ),
    ]
